import type { Metadata } from "next";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { getLoggedUser } from "@/actions/user.actions";
import { decodeVerifyAuthToken, getTokensFromCookies } from "@/actions/utils";
import { User } from "@/models/user";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function MarketingLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    let user: User | null = null;
    try {
        user = await getLoggedUser();
    }
    catch (err) {
        user = null;
    }
    return (
        <>
            <Navigation user={user} />
            <div className="container">
                {children}
            </div>
            <Footer />
        </>
    );
}
